# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListApp(object):
    def setupUi(self, ListApp):
        ListApp.setObjectName("ListApp")
        ListApp.setWindowModality(QtCore.Qt.ApplicationModal)
        ListApp.resize(800, 600)
        ListApp.setMinimumSize(QtCore.QSize(600, 400))
        ListApp.setMaximumSize(QtCore.QSize(1920, 1080))
        ListApp.setBaseSize(QtCore.QSize(800, 600))
        ListApp.setAnimated(True)
        ListApp.setDocumentMode(False)
        ListApp.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(ListApp)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 130, 351, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Suruma")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.AJouterBouton = pageSwitchingButton(self.verticalLayoutWidget, 2) #QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AJouterBouton.setFont(font)
        self.AJouterBouton.setObjectName("AJouterBouton")
        self.verticalLayout.addWidget(self.AJouterBouton)
        self.VisualiserBouton = pageSwitchingButton(self.verticalLayoutWidget, 1) #QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.VisualiserBouton.setFont(font)
        self.VisualiserBouton.setObjectName("VisualiserBouton")
        self.verticalLayout.addWidget(self.VisualiserBouton)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.logsScroll = QtWidgets.QScrollArea(self.page_2)
        self.logsScroll.setGeometry(QtCore.QRect(100, 50, 611, 441))
        self.logsScroll.setAutoFillBackground(True)
        self.logsScroll.setWidgetResizable(True)
        self.logsScroll.setObjectName("logsScroll")
        self.losgScrollContents = QtWidgets.QWidget()
        self.losgScrollContents.setGeometry(QtCore.QRect(0, 0, 609, 439))
        self.losgScrollContents.setObjectName("losgScrollContents")
        #self.textEdit = QtWidgets.QTextEdit(self.losgScrollContents)
        #self.textEdit.setGeometry(QtCore.QRect(0, 20, 611, 401))
        #self.textEdit.setUndoRedoEnabled(False)
        #self.textEdit.setReadOnly(True)
        #self.textEdit.setObjectName("textEdit")
        self.logsScroll.setWidget(self.losgScrollContents)
        self.RetourButton = pageSwitchingButton(self.page_2, 0)
        self.RetourButton.setGeometry(QtCore.QRect(620, 502, 121, 41))
        self.RetourButton.setFont(font)
        self.RetourButton.setObjectName("RetourButton")
        self.RetourButton.clicked.connect(self.switchPage(self.RetourButton.index))
        self.RetourButton.setText("Retour")
        self.stackedWidget.addWidget(self.page_2)
        ListApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ListApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        ListApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ListApp)
        self.statusbar.setObjectName("statusbar")
        ListApp.setStatusBar(self.statusbar)

        self.retranslateUi(ListApp)
        QtCore.QMetaObject.connectSlotsByName(ListApp)

        self.VisualiserBouton.clicked.connect(self.switchPage(self.VisualiserBouton.index))

        rawFile = open("../echantillon.txt", 'r')
        #self.textEdit.setPlainText(rawFile.read())

        #self.logsScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.putContentInScroll(rawFile)


    def retranslateUi(self, ListApp):
        _translate = QtCore.QCoreApplication.translate
        ListApp.setWindowTitle(_translate("ListApp", "ListApp"))
        self.label.setText(_translate("ListApp", "List App"))
        self.AJouterBouton.setText(_translate("ListApp", "Ajouter"))
        self.VisualiserBouton.setText(_translate("ListApp", "Visualiser"))

    def switchPage(self, index):
        def switch():
            self.stackedWidget.setCurrentIndex(index)
        return switch

    def putContentInScroll(self, rawData):
        listData = rawData.readlines()
        scrollWidgetList = []
        current_pos = 0
        for entry in listData:
            scrollWidgetList.append(scrollListWidget(self.losgScrollContents, entry, current_pos))
            current_pos += 60
        self.losgScrollContents.setGeometry(QtCore.QRect(0, 0, 609, 60 * len(listData)))

class pageSwitchingButton(QtWidgets.QPushButton):
    def __init__(self, parent, index):
        QtWidgets.QPushButton.__init__(self, parent)
        self.index = index

class scrollListWidget(QtWidgets.QWidget):
    def __init__(self, parent, data : str, pos):
        split_text = data.split('\t')
        QtWidgets.QWidget.__init__(self, parent)
        print(parent.width())
        self.setGeometry(QtCore.QRect(0, pos, parent.width(), 60))

        idText = QtWidgets.QTextEdit(self)
        idText.setObjectName("idText")
        idText.setStyleSheet("background-color : black; color : white")
        idText.setText(f"ID: {str(split_text[0])}")
        idText.setAlignment(QtCore.Qt.AlignCenter)
        idText.setGeometry(QtCore.QRect(0, 0, parent.width(), 20))
        idText.setReadOnly(True)
        idText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

        #nomText = QtWidgets.QTextEdit(self)
        #nomText.setObjectName(split_text[1])
        #nomText.setAlignment(QtCore.Qt.AlignCenter)
        #nomText.setText(f"Nom: {split_text[1]}")
        #idText.setGeometry(QtCore.QRect(0, 20, parent.width(), 40))



if __name__ == "__main__":
    import sys
    rawFile = open("../echantillon.txt", 'r')
    app = QtWidgets.QApplication(sys.argv)
    ListApp = QtWidgets.QMainWindow()
    ui = Ui_ListApp()
    ui.setupUi(ListApp)
    ListApp.show()
    sys.exit(app.exec_())
