# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.messageBox = QtWidgets.QTextEdit(self.centralwidget)
        self.messageBox.setGeometry(QtCore.QRect(90, 30, 281, 41))
        self.messageBox.setObjectName("messageBox")
        self.upperBox = QtWidgets.QTextEdit(self.centralwidget)
        self.upperBox.setGeometry(QtCore.QRect(90, 160, 291, 70))
        self.upperBox.setReadOnly(True)
        self.upperBox.setObjectName("upperBox")
        self.messageToUpper = QtWidgets.QPushButton(self.centralwidget)
        self.messageToUpper.setGeometry(QtCore.QRect(160, 110, 80, 23))
        self.messageToUpper.setObjectName("messageToUpper")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.messageToUpper.clicked.connect(self.putTextSomewhere)
        #self.messageBox.keyPressEvent(self.capitalizeIt)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.messageToUpper.setText(_translate("MainWindow", "Capitalize"))

    def capitalizeIt(self):
        text = self.messageBox.toPlainText()
        newtext = str()
        for c in text:
            newtext += c.upper()
        self.upperBox.setText(newtext)


    def putTextSomewhere(self):
        text = self.messageBox.toPlainText()
        print(text)
        newtext = str()
        for c in text:
            newtext += c.upper()
        self.upperBox.setText(newtext)


def clicked():
    print("buttonClicked")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
