# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListApp(object):
    def setupUi(self, ListApp):
        ListApp.setObjectName("ListApp")
        ListApp.setWindowModality(QtCore.Qt.ApplicationModal)
        ListApp.resize(800, 600)
        ListApp.setMinimumSize(QtCore.QSize(600, 400))
        ListApp.setMaximumSize(QtCore.QSize(1920, 1080))
        ListApp.setBaseSize(QtCore.QSize(800, 600))
        ListApp.setAnimated(True)
        ListApp.setDocumentMode(False)
        ListApp.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(ListApp)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.stackedWidget.setStyleSheet(".QPushButton{\n"
"border: 2px solid blac;\n"
"border-radius: 8px;\n"
"background-color: qlineargradient(spread:pad, x1:0.542, y1:1, x2:0.543, y2:0, stop:0 rgba(108, 74, 74, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
".QPushButton:hover{\n"
"background-color:rgb(127, 96, 99);\n"
"color:white;\n"
"border: 2px solid black;\n"
"}\n"
"\n"
"QWidget#acceuilWidget{\n"
"background-color:rgb(214, 214, 214);\n"
"border: 2px solid black;\n"
"border-radius: 8px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.accueilPage = QtWidgets.QWidget()
        self.accueilPage.setObjectName("accueilPage")
        self.acceuilWidget = QtWidgets.QWidget(self.accueilPage)
        self.acceuilWidget.setGeometry(QtCore.QRect(250, 130, 351, 251))
        self.acceuilWidget.setObjectName("acceuilWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.acceuilWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 351, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.accueilLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.accueilLayout.setContentsMargins(10, 10, 10, 15)
        self.accueilLayout.setObjectName("accueilLayout")
        self.accueilLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Suruma")
        font.setPointSize(36)
        self.accueilLabel.setFont(font)
        self.accueilLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.accueilLabel.setObjectName("accueilLabel")
        self.accueilLayout.addWidget(self.accueilLabel)
        self.aJouterBouton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.aJouterBouton.setFont(font)
        self.aJouterBouton.setObjectName("aJouterBouton")
        self.accueilLayout.addWidget(self.aJouterBouton)
        self.visualiserBouton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.visualiserBouton.setFont(font)
        self.visualiserBouton.setObjectName("visualiserBouton")
        self.accueilLayout.addWidget(self.visualiserBouton)
        self.stackedWidget.addWidget(self.accueilPage)
        self.visualiserPage = QtWidgets.QWidget()
        self.visualiserPage.setObjectName("visualiserPage")
        self.logsScroll = QtWidgets.QScrollArea(self.visualiserPage)
        self.logsScroll.setGeometry(QtCore.QRect(100, 30, 611, 451))
        self.logsScroll.setAutoFillBackground(True)
        self.logsScroll.setWidgetResizable(True)
        self.logsScroll.setObjectName("logsScroll")
        self.logsScrollContents = QtWidgets.QWidget()
        self.logsScrollContents.setGeometry(QtCore.QRect(0, 0, 609, 449))
        self.logsScrollContents.setObjectName("logsScrollContents")
        self.logsContent = QtWidgets.QTextEdit(self.logsScrollContents)
        self.logsContent.setGeometry(QtCore.QRect(0, 40, 611, 381))
        self.logsContent.setUndoRedoEnabled(False)
        self.logsContent.setReadOnly(True)
        self.logsContent.setObjectName("logsContent")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.logsScrollContents)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, -1, 391, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.logsHeaderLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.logsHeaderLayout.setContentsMargins(0, 0, 0, 0)
        self.logsHeaderLayout.setObjectName("logsHeaderLayout")
        self.headerId = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.headerId.setObjectName("headerId")
        self.logsHeaderLayout.addWidget(self.headerId)
        self.headerNom = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.headerNom.setObjectName("headerNom")
        self.logsHeaderLayout.addWidget(self.headerNom)
        self.headerPrenom = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.headerPrenom.setObjectName("headerPrenom")
        self.logsHeaderLayout.addWidget(self.headerPrenom)
        self.headerAge = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.headerAge.setObjectName("headerAge")
        self.logsHeaderLayout.addWidget(self.headerAge)
        self.logsScroll.setWidget(self.logsScrollContents)
        self.RetourBouton = QtWidgets.QPushButton(self.visualiserPage)
        self.RetourBouton.setGeometry(QtCore.QRect(620, 502, 121, 41))
        self.RetourBouton.setObjectName("RetourBouton")
        self.stackedWidget.addWidget(self.visualiserPage)
        self.ajouterPage = QtWidgets.QWidget()
        self.ajouterPage.setStyleSheet(".QLineEdit{\n"
"margin-right: 20px;\n"
"margin-left: 20px;\n"
"border:none;\n"
"border-right: 2px solid black;\n"
"border-bottom: 2px solid black;\n"
"height:20px\n"
"}\n"
"\n"
".QSpinBox{\n"
"margin-right: 20px;\n"
"margin-left: 20px;\n"
"border:none;\n"
"border-right: 2px solid black;\n"
"border-bottom: 2px solid black;\n"
"}\n"
"\n"
"\n"
".QTextEdit:clicked {\n"
"background-color:rgb(241, 241, 241);\n"
"border-right:2px solid green;\n"
"border-bottom:2px solid green;\n"
"}\n"
"\n"
".QLabel#ajouterLabel{\n"
"text-decoration:underline;\n"
"}\n"
"\n"
".QLabel#errorNom, .QLabel#errorAge, .QLabel#errorPrenom{\n"
"color:red;\n"
"}")
        self.ajouterPage.setObjectName("ajouterPage")
        self.RetourBoutonAjout = QtWidgets.QPushButton(self.ajouterPage)
        self.RetourBoutonAjout.setGeometry(QtCore.QRect(650, 480, 121, 41))
        self.RetourBoutonAjout.setObjectName("RetourBoutonAjout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.ajouterPage)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(200, 100, 441, 360))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.ajouterLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.ajouterLayout.setContentsMargins(0, 0, 0, 0)
        self.ajouterLayout.setSpacing(20)
        self.ajouterLayout.setObjectName("ajouterLayout")
        self.ajouterLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ajouterLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setUnderline(True)
        self.ajouterLabel.setFont(font)
        self.ajouterLabel.setObjectName("ajouterLabel")
        self.ajouterLayout.addWidget(self.ajouterLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.ajouterForm = QtWidgets.QFormLayout()
        self.ajouterForm.setObjectName("ajouterForm")
        self.nomLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.nomLabel.setObjectName("nomLabel")
        self.ajouterForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nomLabel)
        self.nomText = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.nomText.setMinimumSize(QtCore.QSize(0, 22))
        self.nomText.setObjectName("nomText")
        self.ajouterForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nomText)
        self.errorNom = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.errorNom.setMinimumSize(QtCore.QSize(0, 29))
        self.errorNom.setObjectName("errorNom")
        self.ajouterForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.errorNom)
        self.prenomLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.prenomLabel.setObjectName("prenomLabel")
        self.ajouterForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.prenomLabel)
        self.prenomText = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.prenomText.setMinimumSize(QtCore.QSize(0, 22))
        self.prenomText.setObjectName("prenomText")
        self.ajouterForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.prenomText)
        self.errorPrenom = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.errorPrenom.setMinimumSize(QtCore.QSize(0, 29))
        self.errorPrenom.setObjectName("errorPrenom")
        self.ajouterForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.errorPrenom)
        self.ageLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ageLabel.setStyleSheet("")
        self.ageLabel.setObjectName("ageLabel")
        self.ajouterForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ageLabel)
        self.ageText = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.ageText.setMinimumSize(QtCore.QSize(0, 22))
        self.ageText.setObjectName("ageText")
        self.ajouterForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ageText)
        self.errorAge = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.errorAge.setMinimumSize(QtCore.QSize(0, 29))
        self.errorAge.setObjectName("errorAge")
        self.ajouterForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.errorAge)
        self.ajouterLayout.addLayout(self.ajouterForm)
        self.validerBouton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.validerBouton.setMinimumSize(QtCore.QSize(200, 40))
        self.validerBouton.setStyleSheet("")
        self.validerBouton.setObjectName("validerBouton")
        self.ajouterLayout.addWidget(self.validerBouton, 0, QtCore.Qt.AlignHCenter)
        self.errorWidget = QtWidgets.QWidget(self.ajouterPage)
        self.errorWidget.setGeometry(QtCore.QRect(640, 220, 171, 80))
        self.errorWidget.setObjectName("errorWidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.errorWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 160, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.errorLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.errorLayout.setContentsMargins(10, 0, 0, 0)
        self.errorLayout.setObjectName("errorLayout")
        self.stackedWidget.addWidget(self.ajouterPage)
        ListApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ListApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        ListApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ListApp)
        self.statusbar.setObjectName("statusbar")
        ListApp.setStatusBar(self.statusbar)

        self.retranslateUi(ListApp)
        QtCore.QMetaObject.connectSlotsByName(ListApp)

    def retranslateUi(self, ListApp):
        _translate = QtCore.QCoreApplication.translate
        ListApp.setWindowTitle(_translate("ListApp", "ListApp"))
        self.accueilLabel.setText(_translate("ListApp", "List App"))
        self.aJouterBouton.setText(_translate("ListApp", "Ajouter"))
        self.visualiserBouton.setText(_translate("ListApp", "Visualiser"))
        self.headerId.setText(_translate("ListApp", "ID"))
        self.headerNom.setText(_translate("ListApp", "Nom"))
        self.headerPrenom.setText(_translate("ListApp", "Prenom"))
        self.headerAge.setText(_translate("ListApp", "Age"))
        self.RetourBouton.setText(_translate("ListApp", "Retour"))
        self.RetourBoutonAjout.setText(_translate("ListApp", "Retour"))
        self.ajouterLabel.setText(_translate("ListApp", "Ajouter une Nouvelle Entrée"))
        self.nomLabel.setText(_translate("ListApp", "Nom:"))
        self.errorNom.setText(_translate("ListApp", "Nom invalide"))
        self.prenomLabel.setText(_translate("ListApp", "Prenom: "))
        self.errorPrenom.setText(_translate("ListApp", "Prenom invalide"))
        self.ageLabel.setText(_translate("ListApp", "Age: "))
        self.errorAge.setText(_translate("ListApp", "Age invalide"))
        self.validerBouton.setText(_translate("ListApp", "Valider"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ListApp = QtWidgets.QMainWindow()
    ui = Ui_ListApp()
    ui.setupUi(ListApp)
    ListApp.show()
    sys.exit(app.exec_())
